# Generated by Django 4.2.5 on 2023-09-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
    ]
