# Generated by Django 4.2.5 on 2023-09-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_avaliacoes_tipoavaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacoes',
            old_name='tipoavaliacao',
            new_name='tipo',
        ),
    ]
