# Generated by Django 4.2.5 on 2023-09-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_tipoavaliacao_avaliacoes_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoavaliacao',
            old_name='nome',
            new_name='tipo',
        ),
    ]
